# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  #efa716b1aab63601b256afc0cda469f0f7606759
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: efa716b1aab63601b256afc0cda469f0f7606759
  #rev: v0.9.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
